// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using okko.uzapi.Data;

namespace okko.uzapi.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20200719181402_Persons")]
    partial class Persons
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("okko.uzapi.Data.Persons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CelPhone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Firstname")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("IPT")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Lastname")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Location")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Position")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Title")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
